name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      release_type:
        description: 'Release type'
        required: true
        default: 'release'
        type: choice
        options:
          - 'release'
          - 'prerelease'
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string
        default: 'Release created via manual trigger'
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.compute.outputs.tag_name }}
      prerelease: ${{ steps.compute.outputs.prerelease }}
      body: ${{ steps.compute.outputs.body }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute release metadata
        id: compute
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
            TAG_NAME="v$VERSION"
            BODY="${{ github.event.inputs.release_notes }}"
            PRERELEASE=$([ "${{ github.event.inputs.release_type }}" = "prerelease" ] && echo true || echo false)

            if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "Tag $TAG_NAME already exists, will reuse."
            else
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
              git push origin "$TAG_NAME"
            fi
          else
            TAG_REF="${GITHUB_REF#refs/tags/}"
            TAG_NAME="$TAG_REF"
            BODY="Release created from pushed tag $TAG_NAME"
            if echo "$TAG_NAME" | grep -q '-'; then PRERELEASE=true; else PRERELEASE=false; fi
          fi

          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
          echo "body=$BODY" >> $GITHUB_OUTPUT

      - name: Create or update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.compute.outputs.tag_name }}
          name: PReviewer ${{ steps.compute.outputs.tag_name }}
          draft: false
          prerelease: ${{ steps.compute.outputs.prerelease }}
          body: ${{ steps.compute.outputs.body }}
          generate_release_notes: true

  build-and-upload:
    needs: prepare-release
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          # Windows x64
          - os: windows-latest
            platform: windows
            arch: x64
            artifact_patterns: |
              *-x64*.exe
              *Setup.exe
          # Windows ARM64
          - os: windows-latest
            platform: windows
            arch: arm64
            artifact_patterns: |
              *-arm64*.exe
          # macOS (universal or x64)
          - os: macos-latest
            platform: macos
            arch: universal
            artifact_patterns: |
              *.dmg
          # Linux (deb + rpm in one runner)
          - os: ubuntu-latest
            platform: linux
            arch: x64
            artifact_patterns: |
              *.deb
              *.rpm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force
        continue-on-error: true

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        env:
          npm_config_cache: ${{ runner.temp }}/.npm
          ELECTRON_CACHE: ${{ runner.temp }}/.electron

      - name: Update package.json version (manual only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          npm version "$VERSION" --no-git-tag-version

      - name: Build and package
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_CACHE: ${{ runner.temp }}/.electron
        timeout-minutes: 40

      - name: Find release assets
        id: find_assets
        run: |
          set -e

          base_dir="out/make"
          
          # Read multiline patterns
          patterns=$(cat <<'EOF'
          ${{ matrix.artifact_patterns }}
          EOF
          )

          # Create temp file to collect all matches
          assets_file="assets.txt"
          : > "$assets_file"

          # For each non-empty pattern, run find and append results
          while IFS= read -r pattern; do
            [ -z "$pattern" ] && continue
            find "$base_dir" -type f -name "$pattern" -print >> "$assets_file" || true
          done <<EOF2
          $patterns
          EOF2

          # De-duplicate and remove empty lines
          sort -u -o "$assets_file" "$assets_file"
          sed -i.bak '/^[[:space:]]*$/d' "$assets_file" 2>/dev/null || sed -i '/^[[:space:]]*$/d' "$assets_file"
          rm -f "$assets_file.bak" 2>/dev/null || true

          if [ ! -s "$assets_file" ]; then
            echo "No artifacts found matching patterns:"
            echo "$patterns"
            echo "Contents of $base_dir:"
            ls -R "$base_dir" || true
            exit 1
          fi

          # Export as multiline output
          echo "assets<<EOF" >> "$GITHUB_OUTPUT"
          cat "$assets_file" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          echo "Found assets:"
          cat "$assets_file"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare-release.outputs.tag_name }}
          files: ${{ steps.find_assets.outputs.assets }}